### PR TITLE
Update the highlights of dull

### PR DESCRIPTION
**Pull request by Alexis12119**
These are my latest changes on dull and it's working. Hope this can be merge.

### CODE REVIEW

**Comment by adityastomar67** [comment]
Colorscheme is working nicely, we can merge it, but before doing so can you look at the some highlight groups like signcoloumn, concealing highlights, they are breaking whenever switching to it again and again.

**Comment by Alexis12119** [comment]
Is this the problem i need to fix? If yes, maybe i'll try to find some highlight groups

Screenshot (1145)
Screenshot (1146)
Screenshot (1147)

**Comment by Alexis12119** [comment]
Screenshot (1159)

Screenshot (1160)

Screenshot (1161)

Screenshot (1162)

When changing with other colorschemes as you can see it's fine. The only problem is when changing with other style so I came up with this function to solve the problem and It's also implemented in my nvim-config.

**NOTE:** You should restart/reload neovim to take effect when the time comes.
```
-- set colorscheme style based on time
local colorscheme_by_time = function()
  local time = tonumber(os.date "%H")
  if time >= 0 and time <= 15 then
    return "slime"
  elseif time >= 16 and time <= 17 then
    return "sunset"
  else
    return "night"
  end
end

vim.g.dull_style = colorscheme_by_time()
```
@adityastomar67, Can you try it again?

**Comment by adityastomar67** [comment]
That's working good but still the conceal highlights are messed up... Do look it up also please.

**Comment by Alexis12119** [comment]
Sorry, I can't visualize it.

Can you show me the screenshot of the problem? Thanks and sorry for taking so much of your time. Once you send the screenshot, maybe I'll try to fix it tommorow in the afternoon because of school project.

**Comment by adityastomar67** [comment]
It's okay... I'll take care of it.

**Pull request merged**
